// meteor-svelte/imports/ui/Task.svelte
<script>
	import {useTracker} from 'meteor/rdb:svelte-meteor-data';
	import {Tasks} from "../api/tasks.js";

	export let key;
	export let task;
	let showPrivateButton;

	$: currentUser = useTracker(() => Meteor.user());

	$: {
		showPrivateButton = false;
		if ($currentUser) {
			showPrivateButton = task.owner === $currentUser._id;
		}
	}

	function toggleChecked() {
		// Set the checked property to the opposite of its current value
		Meteor.call("tasks.setChecked", task._id, !task.checked);
	};

	function deleteThisTask() {
		Meteor.call("tasks.remove", task._id);
	};

	function togglePrivate() {
		Meteor.call("tasks.setPrivate", task._id, !task.private);
	}

</script>

<li class:checked="{task.checked}"
    class:private="{task.private}">
	<button class="delete" on:click={deleteThisTask}>
		&times;
	</button>

	<input
		type="checkbox"
		readonly
		checked={!!task.checked}
		on:click={toggleChecked}
	/>

    {#if showPrivateButton}
		<button className="toggle-private" on:click="{togglePrivate}">
            { task.private ? "Private" : "Public" }
		</button>
    {/if}

	<span class="text">
    <strong>{ task.username }</strong>
    : { task.text }
  </span>
</li>

// meteor-react/imports/ui/Task.js
import React, {Component} from 'react';
import {Meteor} from 'meteor/meteor';
import classnames from 'classnames';

import {Tasks} from '../api/tasks.js';

// Task component - represents a single todo item
export default class Task extends Component {
	toggleChecked() {
		// Set the checked property to the opposite of its current value
		Meteor.call('tasks.setChecked', this.props.task._id, !this.props.task.checked);
	}

	deleteThisTask() {
		Meteor.call('tasks.remove', this.props.task._id);
	}

	togglePrivate() {
		Meteor.call('tasks.setPrivate', this.props.task._id, !this.props.task.private);
	}

	render() {
		// Give tasks a different className when they are checked off,
		// so that we can style them nicely in CSS
		const taskClassName = classnames({
			checked: this.props.task.checked,
			private: this.props.task.private,
		});

		return (
			<li className={taskClassName}>
				<button className="delete" onClick={this.deleteThisTask.bind(this)}>
					&times;
				</button>

				<input
					type="checkbox"
					readOnly
					checked={!!this.props.task.checked}
					onClick={this.toggleChecked.bind(this)}
				/>

				{this.props.showPrivateButton ? (
					<button className="toggle-private" onClick={this.togglePrivate.bind(this)}>
						{this.props.task.private ? 'Private' : 'Public'}
					</button>
				) : ''}

				<span className="text">
          <strong>{this.props.task.username}</strong>: {this.props.task.text}
        </span>
			</li>
		);
	}
}
