// meteor-react/imports/ui/App.js
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import {Meteor} from 'meteor/meteor';
import {withTracker} from 'meteor/react-meteor-data';

import {Tasks} from '../api/tasks.js';

import Task from './Task.js';
import AccountsUIWrapper from './AccountsUIWrapper.js';

// App component - represents the whole app
class App extends Component {
	constructor(props) {
		super(props);

		this.state = {
			hideCompleted: false,
		};
	}

	handleSubmit(event) {
		event.preventDefault();

		// Find the text field via the React ref
		const text = ReactDOM.findDOMNode(this.refs.textInput).value.trim();

		Meteor.call('tasks.insert', text);

		// Clear form
		ReactDOM.findDOMNode(this.refs.textInput).value = '';
	}

	toggleHideCompleted() {
		this.setState({
			hideCompleted: !this.state.hideCompleted,
		});
	}

	renderTasks() {
		let filteredTasks = this.props.tasks;
		if (this.state.hideCompleted) {
			filteredTasks = filteredTasks.filter(task => !task.checked);
		}
		return filteredTasks.map((task) => {
			const currentUserId = this.props.currentUser && this.props.currentUser._id;
			const showPrivateButton = task.owner === currentUserId;

			return (
				<Task
					key={task._id}
					task={task}
					showPrivateButton={showPrivateButton}
				/>
			);
		});
	}

	render() {
		return (
			<div className="container">
				<header>
					<h1>Todo List ({this.props.incompleteCount})</h1>

					<label className="hide-completed">
						<input
							type="checkbox"
							readOnly
							checked={this.state.hideCompleted}
							onClick={this.toggleHideCompleted.bind(this)}
						/>
						Hide Completed Tasks
					</label>

					<AccountsUIWrapper/>

					{this.props.currentUser ?
						<form className="new-task" onSubmit={this.handleSubmit.bind(this)}>
							<input
								type="text"
								ref="textInput"
								placeholder="Type to add new tasks"
							/>
						</form> : ''
					}
				</header>

				<ul>
					{this.renderTasks()}
				</ul>
			</div>
		);
	}
}

export default withTracker(() => {
	Meteor.subscribe('tasks');

	return {
		tasks: Tasks.find({}, {sort: {createdAt: -1}}).fetch(),
		incompleteCount: Tasks.find({checked: {$ne: true}}).count(),
		currentUser: Meteor.user(),
	};
})(App);

// meteor-svelte/imports/ui/App.svelte
<script>
	import {Meteor} from "meteor/meteor";
	import {onMount} from 'svelte';
	import {useTracker} from 'meteor/rdb:svelte-meteor-data';
	import {BlazeTemplate} from 'meteor/svelte:blaze-integration';
	import Task from './Task.svelte';
	import {Tasks} from '../api/tasks.js'

	let newTask = "";
	let hideCompleted = false;
	let tasks;
	let currentUser;

	onMount(async () => {
		Meteor.subscribe('tasks');
	});

	$: incompleteCount = useTracker(() => Tasks.find({checked: {$ne: true}}).count());

	$: currentUser = useTracker(() => Meteor.user());

	const taskStore = Tasks.find({}, {sort: {createdAt: -1}});
	$: {
		tasks = $taskStore;
		if (hideCompleted) {
			tasks = tasks.filter(task => !task.checked);
		}
	}
	;

	function handleSubmit(event) {
		Meteor.call("tasks.insert", newTask);

		// Clear form
		newTask = "";
	};

</script>

<div class="container">
	<header>
		<h1>Todo List ({ $incompleteCount })</h1>
		<label className="hide-completed">
			<input
				type="checkbox"
				bind:checked={hideCompleted}
			/>
			Hide Completed Tasks
		</label>

		<BlazeTemplate template="loginButtons"/>

        {#if $currentUser}
			<form class="new-task" on:submit|preventDefault={handleSubmit}>
				<input
					type="text"
					placeholder="Type to add new tasks"
					bind:value={newTask}
				/>
			</form>
        {/if}
	</header>
	<ul>
        {#each tasks as task}
			<Task
				key={task._id}
				task={task}
			/>
        {/each}
	</ul>
</div>
